if exists (select 1
            from  sys.views
            where  name    = 'GESTION_MESSAGES_VUE')
   drop view GESTION_MESSAGES_VUE
go

create view GESTION_MESSAGES_VUE (NOMUTILISATEUR, PSEUDO, DTESUJET, TITRESUJET, NOMRUBRIQUE, IDSUJET, DESCSUJET, TEXTEREPONSE, DTREPONSE)
as 
select NOM_UTILISATEUR, PSEUDO_UTILISATEUR, DATE_CREATION, TITRE_SUJET, NOM_RUBRIQUE, s.ID_SUJET, DESCRIPTION_SUJET, TEXTE_REPONSE, DATE_REPONSE
from SUJETS s
left join REPONSES re on s.ID_SUJET = re.ID_SUJET 
join UTILISATEURS u on u.ID_UTILISATEUR = s.ID_UTILISATEUR
join RUBRIQUES ru on s.ID_RUBRIQUE = ru.ID_RUBRIQUE
go