if object_id('BUILDUTILISATEURBYNOMUTILISATEUR', 'p') is not null
drop procedure BUILDUTILISATEURBYNOMUTILISATEUR
go

create procedure BUILDUTILISATEURBYNOMUTILISATEUR

@nomutilisateur varchar(50)

as

begin

select ID_UTILISATEUR, NOM_UTILISATEUR, PRENOM_UTILISATEUR, PSEUDO_UTILISATEUR, DATE_INSCRIPTION 
from UTILISATEURS where NOM_UTILISATEUR = @nomutilisateur

end
go